<a href="https://colab.research.google.com/github/otorregrosa/LinearAlg/blob/main/Lab_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$ A = \left\{ \begin{array}\\ 9x+y+9z=20\\ 3x+9y+5z=18 \\ 7x+2y+8z=25 \end{array} \right. $$

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
x = np.array([
    [9,1,9],
    [3,9,5],
    [7,2,8]
])

y = np.array([
    [20],
    [18],
    [25]
])

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)


x_inv = np.linalg.inv(x)
print("\nResult: ")
print(x_inv @ y)

Matrix x: 
 [[9 1 9]
 [3 9 5]
 [7 2 8]]

Matrix y: 
 [[20]
 [18]
 [25]]

Result: 
[[-8.57142857]
 [-1.21428571]
 [10.92857143]]


In [8]:
x_inv1 = np.linalg.solve(x, y)

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)

print("\nResult: ")
print(x_inv1)

Matrix x: 
 [[9 1 9]
 [3 9 5]
 [7 2 8]]

Matrix y: 
 [[20]
 [18]
 [25]]

Result: 
[[-8.57142857]
 [-1.21428571]
 [10.92857143]]


$Let : \\ 
a = \text{bag of rice}, b = \text{kilogram of meat}, c = \text{piece of egg} \\ \\
M_1: 30a + 10b + 150c = 9,500 \\
M_2: 18a + 18b + 200c = 13,000 \\
M_3: 40a + 32b + 250c = 16,500$



$$\begin{bmatrix}30&10&150\\18&18&200\\40&32&250\end{bmatrix}\cdot\begin{bmatrix}a\\b\\c\end{bmatrix} = \begin{bmatrix}9,500\\13,000\\16,500\end{bmatrix}$$

In [41]:
quantities = np.array([
    [30, 10, 150],
    [18, 18, 200],
    [40, 32, 250]
])
cost = np.array([
    [9500],
    [13000],
    [16500]
])

In [42]:
prices = np.linalg.inv(quantities) @ cost 
print('The price of one sack of flour is: PHP {:.2f}'.format(float(prices[0])))
print('The price of one pack of yeast is: PHP {:.2f}'.format(float(prices[1])))
print('The price of one piece of egg is: PHP {:.2f}'.format(float(prices[2])))


The price of one sack of flour is: PHP -6.88
The price of one pack of yeast is: PHP 38.99
The price of one piece of egg is: PHP 62.11


In [40]:
np.linalg.solve(quantities, cost) 

array([[-6.88073394],
       [38.99082569],
       [62.11009174]])