<a href="https://colab.research.google.com/github/otorregrosa/LinearAlg/blob/main/lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [4]:
A = np.array([
    [7,2,8],
    [3,6,9],
    [5,7,9]
])
B = np.array([
    [9,1,9],
    [3,9,5],
    [3,5,7]
])
C = np.array([
    [2,4,6],
    [9,8,7],
    [6,5,4]
])
print("A = \n", A)
print("B = \n", B)
print("C = \n", C)

A = 
 [[7 2 8]
 [3 6 9]
 [5 7 9]]
B = 
 [[9 1 9]
 [3 9 5]
 [3 5 7]]
C = 
 [[2 4 6]
 [9 8 7]
 [6 5 4]]


In [5]:
AT1 = np.transpose(A)
AT2 = A.T
np.array_equiv(AT1, AT2)

True

In [6]:
B.shape
np.transpose(B).shape
B.T.shape

(3, 3)

$$ A \cdot B \neq B \cdot A $$

In [9]:
print("A@B = \n", A @ B)
print("B@A = \n", B @ A)
np.array_equiv(A @ B, B @ A)

A@B = 
 [[ 93  65 129]
 [ 72 102 120]
 [ 93 113 143]]

B@A = 
 [[111  87 162]
 [ 73  95 150]
 [ 71  85 132]]


False

$$A \cdot (B \cdot C) = (A \cdot B) \cdot C$$

In [10]:
print("A@(B@C) = \n", (A @ (B@C)))
print("(A@B)@C = \n", ((A@B) @ C))
np.array_equiv( (A @ (B@C)), ((A@B) @ C))

A@(B@C) = 
 [[1545 1537 1529]
 [1782 1704 1626]
 [2061 1991 1921]]

(A@B)@C = 
 [[1545 1537 1529]
 [1782 1704 1626]
 [2061 1991 1921]]


True

$$A \cdot (B + C) = (A \cdot B) + (A \cdot C)$$

In [11]:
print("A@(B+C) = \n", (A @ (B+C)))
print("(A@B)+(A@C) = \n", ((A@B) + (A@C)))
np.array_equiv( (A @ (B+C)), ((A@B) + (A@C)))

A@(B+C) = 
 [[173 149 217]
 [186 207 216]
 [220 234 258]]

(A@B)+(A@C) = 
 [[173 149 217]
 [186 207 216]
 [220 234 258]]


True

$$(B + C) \cdot A = (B \cdot A) + (C \cdot A)$$

In [12]:
print("(B+C)@A = \n", ((B+C) @ A))
print("(B@A)+(C@A) = \n", ((B@A) + (C@A)))
np.array_equiv( ((B+C) @ A), ((B@A) + (C@A)))

(B+C)@A = 
 [[167 157 268]
 [195 210 357]
 [148 155 261]]
(B@A)+(C@A) = 
 [[167 157 268]
 [195 210 357]
 [148 155 261]]


True

$$A \cdot D = A$$

In [13]:
D = np.eye(3, dtype=int)
print("A@D = \n", A @ D)
print("A = \n", A)
np.array_equiv((A @ D), A)

A@D = 
 [[7 2 8]
 [3 6 9]
 [5 7 9]]
A = 
 [[7 2 8]
 [3 6 9]
 [5 7 9]]


True

$$A \cdot \emptyset = \emptyset$$

In [14]:
Zero_Amat = np.zeros(A.shape)
A_zero = A @ np.zeros(A.shape)
print("A @ \emptyset =")
print(A_zero)
print("\nEmpty set/matrix =")
print(Zero_Amat)
np.array_equal(A_zero, Zero_Amat)

A @ \emptyset =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Empty set/matrix =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True